languageCode = 'en-us'
title = 'sthings'
theme = 'github-style'
author = "phermann"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Patrick Hermann"
  description = "using modularity to speed up parallel builds"
  github = "stuttgart-things"
  #facebook = "MeiK2333"
  #twitter = "MeiK2333"
  #linkedin = "MeiK2333"
  #instagram = "MeiK2333"
  #tumblr = "MeiK2333"
  email = "patrick.hermann@sva.de"
  url = "https://github.com/stuttgart-things"
  keywords = "sthings, golang, ansible, kubernetes, linux, machineShop"
  rss = true
  lastmod = true
  favicon = "/images/sthings-logo.png"
  avatar = "/images/sthings-city.png"
  headerIcon = "/images/github-mark-white.png"
  location = "Stuttgart"
  userStatusEmoji = "😀"
  enableGitalk = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"
