# Exclude URLs and mail addresses from checking (supports regex).
exclude = [
    '.+\.sva\.de',
    '.+\.default\.svc',        # exclude k8s services
    '.+\.svc\.cluster\.local', # exclude k8s services
    '\d+\.\d+\.\d+\.\d+',      # exclude IP addresses
    '.+\.tekton-pipelines',    # exclude tekton pipelines
    '\$%7B.+%7D',              # exclude templating ${...}
]

# Remap URI matching pattern to different URI.
remap = ['https://charts.bitnami.com/bitnami https://charts.bitnami.com/']

# Exclude all private IPs from checking.
# Equivalent to setting `exclude_private`, `exclude_link_local`, and
# `exclude_loopback` to true.
exclude_all_private = true