---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/platform-engineering-showcase/refs/heads/main/taskfiles/git.yaml

vars:
  PROJECT_NAME:
    sh: echo ${PWD##*/}
  BRANCH:
    sh: if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then echo $(git rev-parse --abbrev-ref HEAD); else echo main ; fi


dotenv: ['.env', '{{.HOME}}/.env']

tasks:
  serve-presentation:
    desc: Watch files in presentation/ and rerun task serve on changes
    cmds:
      - |
        find {{ .dir }}/{{ .presentation }} -type f | entr -r \
        dagger call -m {{ .daggerModule }} serve \
        --config {{ .dir }}/{{ .presentation }}/hugo.toml \
        --content {{ .dir }}/{{ .presentation }} \
        --port {{ .port }} \
        up --progress plain

    silent: true
    vars:
      daggerModule: github.com/stuttgart-things/dagger/hugo@v0.12.0
      port: 4427
      dir: presentations
      presentation:
        sh: gum choose $(basename -a {{ .dir }}/*/ | grep -v '^tests$')

  lint-repository:
    desc: Lint repository using Dagger blueprint function
    cmds:
      - |
        dagger call -m {{ .MODULE }}@{{ .VERSION }} {{ .FUNCTION }} \
        --src {{ .CODE_DIR }} \
        export --path {{ .EXPORT_PATH }}
    vars:
      MODULE: github.com/stuttgart-things/blueprints/repository-linting
      VERSION: v1.15.0
      FUNCTION: validate-multiple-technologies
      CODE_DIR: "./"
      EXPORT_PATH: /tmp/docs-repo-findings.txt

  build-s3-push:
    desc: Build static content
    cmds:
      - |
        # CLEAN UP
        rm -rf {{ .OUTPUT_PATH_STATIC }} || true

        # BUILD STATIC CONTENT
        dagger call -m {{ .HUGO_MODULE }} \
        build-sync-export \
        --name {{ .presentation }} \
        --config {{ .dir }}/{{ .presentation }}/hugo.toml \
        --content {{ .dir }}/{{ .presentation }} \
        --endpoint {{ .s3Endpoint }} \
        --bucket-name {{ .presentation }} \
        --insecure={{ .s3Insecure }} \
        --access-key=env:MINIO_USER \
        --secret-key=env:MINIO_PASSWORD \
        --alias-name artifacts \
        export \
        --path {{ .OUTPUT_PATH_STATIC }}

        echo "FROM scratch" > {{ .OUTPUT_PATH_STATIC }}/Dockerfile
        echo "COPY . /" >> {{ .OUTPUT_PATH_STATIC }}/Dockerfile

        dagger call -m {{ .DOCKER_MODULE }} \
        build-and-push \
        --source {{ .OUTPUT_PATH_STATIC }} \
        --repository-name {{ .REPOSITORY }}/{{ .presentation }} \
        --registry-url {{ .REGISTRY }} \
        --version {{ .VERSION }} \
        --progress plain  \
        --with-registry-username=env:GITHUB_USER \
        --with-registry-password=env:GITHUB_TOKEN \
        -vv

    vars:
      DOCKER_MODULE: github.com/stuttgart-things/dagger/docker@v0.11.1
      HUGO_MODULE: github.com/stuttgart-things/dagger/hugo@v0.12.0
      dir: presentations
      s3Endpoint: https://play.min.io
      s3Insecure: true
      presentation:
        sh: gum choose $(basename -a {{ .dir }}/*/)
      OUTPUT_PATH_STATIC: /tmp/hugo/static/{{ .presentation }}
      VERSION:
        sh: date +"%Y%m%d-%H%M%S"
      REPOSITORY: stuttgart-things
      REGISTRY: ghcr.io

  build:
    desc: Build static content
    cmds:
      - |
        # CLEAN UP
        rm -rf {{ .OUTPUT_PATH_STATIC }} || true

        # BUILD STATIC CONTENT
        dagger call -m {{ .MODULE }} \
        build-and-export \
        --name {{ .presentation }} \
        --config {{ .dir }}/{{ .presentation }}/hugo.toml \
        --content {{ .dir }}/{{ .presentation }} \
        export --path {{ .OUTPUT_PATH_STATIC }}
    vars:
      #MODULE: github.com/stuttgart-things/dagger/hugo@v0.11.0
      MODULE: /home/sthings/projects/dagger/hugo
      dir: presentations
      presentation:
        sh: gum choose $(basename -a {{ .dir }}/*/)
      OUTPUT_PATH_STATIC: /tmp/hugo/static/{{ .presentation }}

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"

  default:
    desc: Default task is select & do (work)
    cmds:
      - task do

  lychee:
    desc: Check links with lychee
    cmds:
      - |
        LYCHEE=$(command -v lychee 2>/dev/null) || true
        if [ -z "$LYCHEE" ]; then
          LYCHEE_VERSION='v0.15.1'	# current stable version
          LYCHEE_TMP='/tmp/'
          LYCHEE_FILE="${LYCHEE_TMP}lychee-${LYCHEE_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          wget "https://github.com/lycheeverse/lychee/releases/download/${LYCHEE_VERSION}/lychee-${LYCHEE_VERSION}-x86_64-unknown-linux-gnu.tar.gz" -O "$LYCHEE_FILE"
          tar -C /usr/local/bin -xzvf "$LYCHEE_FILE"
        fi
      - git ls-files | grep -E -v '.png$|.ico$' | xargs lychee
