---
version: 3

vars:
  KUBECONFIG_FOLDER: ~/.kube

tasks:
  install:
    desc: Install k3s cluster
    cmds:
      - |
        OUTPUT_PATH=$(gum input --value "/tmp/k3s-config.yaml" --prompt "Where to save k3s config? [default: /tmp/k3s-config.yaml]: ")
        K3S_VERSION=$(gum input --value "v1.33.1+k3s1" --prompt "K3S VERSION? [default: v1.33.1+k3s1]: ")
        CLUSTER_NAME=$(gum input --value "k3s" --prompt "CLUSTER NAME? [default: k3s]: ")
        PATH_KUBECONFIG=$HOME/.kube

        cat <<EOF > ${OUTPUT_PATH}
        write-kubeconfig-mode: 0644
        flannel-backend: none
        disable-kube-proxy: true
        disable-network-policy: true
        cluster-init: true
        disable:
          - servicelb
          - traefik
        EOF

        echo "Writing k3s config to ${OUTPUT_PATH}..."

        cat ${OUTPUT_PATH}

        gum confirm "Do you want to deploy k3s?" || exit 0

        #INSTALL
        curl -sfL https://get.k3s.io | K3S_CONFIG_FILE=${OUTPUT_PATH} K3S_VERSION=${K3S_VERSION} sudo sh -

        # KUBECONFIG
        mkdir ${PATH_KUBECONFIG} || true
        sudo cp /etc/rancher/k3s/k3s.yaml ${PATH_KUBECONFIG}/${CLUSTER_NAME}
        sudo chmod 777 ${PATH_KUBECONFIG}/${CLUSTER_NAME}

        # VEERIFY
        kubectl get nodes --kubeconfig ${PATH_KUBECONFIG}/${CLUSTER_NAME}

  uninstall:
    desc: Uninstall k3s cluster
    cmds:
      - |
        sudo /usr/local/bin/k3s-uninstall.sh || true