---
apiVersion: argoproj.io/v1alpha1
kind: Application
  name: test2
  namespace: argocd
spec:   
  project: pve-dev51
  source:
    repoURL: 'https://github.com/stuttgart-things/stuttgart-things.git'
    path: machineShop/argo-cd/avp-manifest
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
  destination:
    server: 'https://10.31.103.122:6443'
    namespace: default
