---
# BASE-OS
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: AnsibleRun
metadata:
  name: baseos-sandiego-1
  namespace: default
spec:
  pipelineRunName: baseos-sandiego5
  inventory:
    - "all+[\"sandiego.labul.sva.de\"]"
  playbooks:
    - "ansible/playbooks/prepare-env.yaml"
    - "ansible/playbooks/base-os.yaml"
  ansibleVarsFile:
    - "manage_filesystem+-true"
    - "update_packages+-true"
    - "install_requirements+-true"
    - "install_motd+-true"
    - "username+-sthings"
    - "lvm_home_sizing+-'15%'"
    - "lvm_root_sizing+-'35%'"
    - "lvm_var_sizing+-'50%'"
    - "send_to_msteams+-true"
    - "reboot_all+-false"
  gitRepoUrl: https://github.com/stuttgart-things/stuttgart-things.git
  gitRevision: main
  providerRef:
    name: kubernetes-incluster
  vaultSecretName: vault
  pipelineNamespace: tektoncd
  workingImage: eu.gcr.io/stuttgart-things/sthings-ansible:9.21.0
  roles:
    - "https://github.com/stuttgart-things/install-requirements.git"
    - "https://github.com/stuttgart-things/manage-filesystem.git"
    - "https://github.com/stuttgart-things/install-configure-vault.git"
---
# PDNS
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: AnsibleRun
metadata:
  name: pdns-entry-pve-gude
  namespace: default
spec:
  pipelineRunName: pdns-entry-pve-gude1
  inventory:
    - "all+[\"localhost\"]"
  playbooks:
    - "ansible/playbooks/pdns-ingress-entry.yaml"
  ansibleVarsFile:
    - "pdns_url+-https://pdns-pve.labul.sva.de:8443"
    - "entry_zone+-sthings-pve.labul.sva.de."
    - "ip_address+-10.31.103.18"
    - "hostname+-gude"
  gitRepoUrl: https://github.com/stuttgart-things/stuttgart-things.git
  gitRevision: main
  providerRef:
    name: kubernetes-incluster
  vaultSecretName: vault
  pipelineNamespace: tektoncd
  workingImage: eu.gcr.io/stuttgart-things/sthings-ansible:9.2.0
  roles:
    - "https://github.com/stuttgart-things/install-configure-powerdns.git"
---
# RKE2
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: AnsibleRun
metadata:
  name: rke2-manager-sthings
  namespace: default
spec:
  pipelineRunName: rke2-manager-sthings
  inventory:
    - "initial_master_node+[\"manager-sthings.labul.sva.de\"]"
    - "additional_master_nodes+[\"\"]"
  playbooks:
    - "ansible/playbooks/prepare-env.yaml"
    - "ansible/playbooks/base-os.yaml"
    - "ansible/playbooks/deploy-rke2.yaml"
    - "ansible/playbooks/upload-kubeconfig-vault.yaml"
  ansibleVarsFile:
    - "manage_filesystem+-true"
    - "update_packages+-true"
    - "install_requirements+-true"
    - "install_motd+-true"
    - "username+-sthings"
    - "lvm_home_sizing+-'15%'"
    - "lvm_root_sizing+-'35%'"
    - "lvm_var_sizing+-'50%'"
    - "send_to_msteams+-true"
    - "reboot_all+-false"
    - "cluster_name+-sthings-app1"
    - "rke2_k8s_version+-1.28.7"
    - "rke2_release_kind+-rke2r1"
    - "cluster_setup+-multinode"
    - "target_host+-manager-sthings.labul.sva.de"
    - "kubeconfig_path+-/etc/rancher/rke2/rke2.yaml"
    - "secret_path_kubeconfig+-kubeconfigs"
  gitRepoUrl: https://github.com/stuttgart-things/stuttgart-things.git
  gitRevision: main
  providerRef:
    name: kubernetes-incluster
  vaultSecretName: vault
  pipelineNamespace: tektoncd
  workingImage: eu.gcr.io/stuttgart-things/sthings-ansible:9.2.0
  roles:
    - "https://github.com/stuttgart-things/install-requirements.git"
    - "https://github.com/stuttgart-things/manage-filesystem.git"
    - "https://github.com/stuttgart-things/install-configure-vault.git"
    - "https://github.com/stuttgart-things/deploy-configure-rke"
