---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-kaniko-image-scaffolder
spec:
  pipelineRef:
    name: build-kaniko-image
  workspaces:
    - name: dockerconfig
      csi:
        driver: 'secrets-store.csi.k8s.io'
        readOnly: true
        volumeAttributes:
          secretProviderClass: vault-kaniko-creds
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 2Gi
    - name: basic-auth
      csi:
        driver: 'secrets-store.csi.k8s.io'
        readOnly: true
        volumeAttributes:
          secretProviderClass: vault-git-creds
  params:
    - name: gitRepoUrl
      value: https://github.boschdevcloud.com/HEP4BUE/scaffolder.git
    - name: gitRevision
      value: add-tekton-pipelinerun-template
    - name: gitWorkspaceSubdirectory
      value: "/kaniko/scaffolder"
    - name: dockerfile
      value: "Dockerfile"
    - name: context
      value: "/kaniko/scaffolder/"
    - name: image
      value: akswkstekton.azurecr.io/scaffolder
    - name: tag
      value: v3
      