module "manager-dev" {
  source                 = "github.com/stuttgart-things/vsphere-vm?ref=v1.7.5-2.7.0"
  vm_count               = 1
  vsphere_vm_name        = "manager-dev"
  vm_memory              = 12288
  vm_disk_size           = "128"
  vm_num_cpus            = 12
  firmware               = "bios"
  vsphere_vm_folder_path = "stuttgart-things/dev"
  vsphere_datacenter     = "/NetApp-HCI-Datacenter"
  vsphere_datastore      = "/NetApp-HCI-Datacenter/datastore/DatastoreCluster/NetApp-HCI-Datastore-02"
  vsphere_resource_pool  = "Resources"
  vsphere_network        = "/NetApp-HCI-Datacenter/network/tiab-prod"
  vsphere_vm_template    = "/NetApp-HCI-Datacenter/vm/stuttgart-things/vm-templates/ubuntu23"
  vm_ssh_user            = var.vm_ssh_user
  vm_ssh_password        = var.vm_ssh_password
  bootstrap              = ["echo STUTTGART-THINGS"]
  annotation             = "VSPHERE-VM BUILD w/ TERRAFORM FOR STUTTGART-THINGS"
  vsphere_user           = var.vsphere_user
  vsphere_password       = var.vsphere_password
  vsphere_server         = var.vsphere_server
}

variable "vsphere_server" {
  default     = "10.100.135.50"
  description = "vsphere server"
}

variable "vsphere_user" {
  default     = "patrick.hermann@lab.sva.de"
  description = "password of vsphere user"
}

variable "vsphere_password" {
  default     = false
  description = "password of vsphere user"
}

variable "vm_ssh_user" {
  default     = "sthings"
  description = "username of ssh user for vm"
}

variable "vm_ssh_password" {
  default     = false
  description = "password of ssh user for vm"
}
