---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: slides
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
featureGates:
  ImageVolume: true
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
    image: kindest/node:v1.33.1
    extraMounts:
      - hostPath: /mnt/slides-node1
        containerPath: /data
  - role: worker
    image: kindest/node:v1.33.1
    extraMounts:
      - hostPath: /mnt/slides-node2
        containerPath: /data