---
jobs:
  collection-build:
  - name: Build Collection
    uses: dagger/dagger-for-github@v8.0.0
    with:
      version: 0.18.9
      verb: call
      module: github.com/stuttgart-things/dagger/ansible@$11.1.0
      args: |
        run-collection-build-pipeline
        --src collections/${{ inputs.collection }}
        --progress plain export
        --path=build
