---
name: Dispatch Hugo
on:
  workflow_dispatch:
    inputs:
      runs-on:
        required: true
        type: string
        default: ghr-docs-sthings-cicd

jobs:
  build-hugo:
    name: Build Hugo
    runs-on: ${{ inputs.runs-on }}
    container:
      image: klakegg/hugo:0.107.0-ext-alpine
    environment: k8s
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "Creating hugo site"
          hugo new site sthings -f "yaml"
          git clone https://github.com/MeiK2333/github-style ./sthings/themes/github-style
          mkdir -p ./sthings/content/post

          ls -lta
        
          bash hugo/create-sthings.sh

          #cp -R hugo/*.html ./sthings/content/post
          #cp hugo/sthings-logo.png ./sthings/themes/github-style/static/images/avatar.png
          ls -lta sthings/content/post

      - uses: actions/upload-artifact@v3
        with:
          name: hugo-dev
          path: sthings

      - run: cd sthings && hugo --verbose --destination ../public

      - uses: actions/upload-artifact@v3
        with:
          name: hugo-public
          path: public