---
name: Build Static Content
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  markdown-lint:
    name: Lint markdown files
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-markdown-lint.yaml@mc2024-05-14
    with:
      environment-name: k8s
      runs-on: ghr-docs-skyami-cicd
      continue-error: true
      alpine-version: 3.19.0
      lintprofile-path: .markdownlint.rb
      artifact-name: md-lint
      
  yaml-lint:
    name: Lint yaml files
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-yaml-lint.yaml@mc2024-05-14
    with:
      environment-name: k8s
      runs-on: ghr-docs-skyami-cicd
      continue-error: true
      yamllint-version: 1
      lintprofile-path: .yamllint
      artifact-name: yaml-lint
      
#  build-hugo:
#    name: Build hugo
##    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-hugo-build.yaml@mc2024-05-14
 #   needs:
#      - markdown-lint
#      - yaml-lint
#    with:
#      environment-name: k8s
#      runs-on: ghr-docs-skyami-cicd
#      image: floryn90/hugo:0.126.1-ext-ubuntu-ci
#      creation-script-path: hugo/create-content.sh
#      site-name: blog
#      s3-bucket: hugo
#      s3-endpoint: https://artifacts.app1.sthings-vsphere.labul.sva.de:443
#    secrets: inherit
