---
name: Build Static Content
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  markdown-lint:
    name: Lint markdown files
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-markdown-lint.yaml@main
    with:
      environment-name: k8s
      runs-on: ghr-docs-labda-test
      continue-error: true
      alpine-version: 3.19.0
      lintprofile-path: .markdownlint.rb
      artifact-name: md-lint
      
  yaml-lint:
    name: Lint yaml files
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-yaml-lint.yaml@main
    with:
      environment-name: k8s
      runs-on: ghr-docs-labda-test
      continue-error: true
      yamllint-version: 1
      lintprofile-path: .yamllint
      artifact-name: yaml-lint
      
  build-hugo:
    name: Build hugo
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-hugo-build.yaml@main
    with:
      environment-name: k8s
      runs-on: ghr-docs-labda-test
      image: dcjulian29/hugo:0.125.5
      creation-script-path: hugo/create-content.sh
      site-name: blog
      s3-bucket: hugo
      s3-endpoint: https://artifacts.app1.sthings-vsphere.labul.sva.de:443
