name: Build Static Content
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  Markdown-Lint:
    runs-on: docs-runner-set-4
    container:
      image: alpine:3.16.2
    #defaults:
      #run:
       # working-directory: /
    environment: k8s
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "🎉 Starting markdown lint!"
          ls -lta
          apk add --update --no-cache ruby-full && gem install mdl --no-document
          mdl . -s .markdownlint.rb | tee ./md-lint.txt
      - uses: actions/upload-artifact@v3
        with:
          name: md-lint
          path: md-lint.txt

  yaml-Lint:
    runs-on: docs-runner-set-4
    container:
      image: cytopia/yamllint:1
    environment: k8s
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "🎉 Starting yaml lint!"
          ls -lta
          yamllint
      - uses: actions/upload-artifact@v3
        with:
          name: yaml-lint
          path: yaml-lint.txt



 # Trivy:
 #   runs-on: docs-runner-set-4
 #   container: aquasec/trivy:0.46.0
 #   environment: k8s
 #   steps:
 #     - run: |
 #         echo "🎉 TRIVY!"
 #         cat /etc/os-release
 #         whoami
 #         ls -lta
 #         trivy version
 #         trivy image python:3.4-alpine
 #         echo ${{secrets.KUBECONFIG}}
