name: Build Static Content
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      
jobs:
  Markdown-Lint:
    runs-on: docs-runner-set-4
    container: markdownlint/markdownlint:0.13.0
    defaults:
      run:
        working-directory: /tmp
    environment: k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "🎉 Starting markdown lint!"
          ls -lta
          mdl --help

 # Trivy:
 #   runs-on: docs-runner-set-4
 #   container: aquasec/trivy:0.46.0
 #   environment: k8s
 #   steps:
 #     - run: |
 #         echo "🎉 TRIVY!"
 #         cat /etc/os-release
 #         whoami
 #         ls -lta
 #         trivy version
 #         trivy image python:3.4-alpine
 #         echo ${{secrets.KUBECONFIG}}

