name: Build Static Content
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  Markdown-Lint:
    runs-on: docs-runner-set-4
    container:
      image: alpine:3.16.2
    #defaults:
      #run:
       # working-directory: /
    environment: k8s
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "🎉 Starting markdown lint!"
          ls -lta
          apk add --update --no-cache ruby-full && gem install mdl --no-document
          mdl . -s .markdownlint.rb | tee ./md-lint.txt
      - uses: actions/upload-artifact@v3
        with:
          name: md-lint
          path: md-lint.txt

  Yaml-Lint:
    runs-on: docs-runner-set-4
    container:
      image: cytopia/yamllint:1
    environment: k8s
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "🎉 Starting yaml lint!"
          ls -lta
          yamllint . --format github | tee ./yaml-lint.txt
      - uses: actions/upload-artifact@v3
        with:
          name: yaml-lint
          path: yaml-lint.txt

  Build-Hugo:
    runs-on: docs-runner-set-4
    container:
      image: klakegg/hugo:0.107.0-ext-alpine
    environment: k8s
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "Creating hugo blog"
          hugo new site blog -f "yaml"
          cp -R hugo/config.yaml ./blog
          git clone https://github.com/alex-shpak/hugo-book ./blog/themes/hugo-book
          cp -R ./blog/themes/hugo-book/exampleSite/content.en/* ./blog/content
          ls -lta ./blog
          cd blog && hugo --verbose --destination ../public
      - uses: actions/upload-artifact@v3
        with:
          name: hugo-public
          path: public

      - name: Fix permissions
        run: |
          chmod -c -R +rX "blog/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

  Deploy-Hugo-Site:
    runs-on: docs-runner-set-4
    needs: Build-Hugo
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    container:
      image: locietta/loia-dev-base:node
    environment: k8s
    continue-on-error: false
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: hugo-public

      - name: Checkout code
        run: |
          ls -lta

      - uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action

 # Trivy:
 #   runs-on: docs-runner-set-4
 #   container: aquasec/trivy:0.46.0
 #   environment: k8s
 #   steps:
 #     - run: |
 #         echo "🎉 TRIVY!"
 #         cat /etc/os-release
 #         whoami
 #         ls -lta
 #         trivy version
 #         trivy image python:3.4-alpine
 #         echo ${{secrets.KUBECONFIG}}
